name: Main Tests

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2.2.0

    - name: Set up julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.9.1

    - name: Build package
      uses: julia-actions/julia-buildpkg@v1

    - name: Run tests
      uses: julia-actions/julia-runtest@v1

      
